adventureworks_project:
  outputs:
    dev:
      account: tt58410.sa-east-1.aws
      database: ADVENTUREWORKS_DATABASE
      password: pas!!ssword123
      role: ADVENTUREWORKS_ROLE
      schema: dev_andressa
      threads: 4
      type: snowflake
      user: ADVENTUREWORKS_USER
      warehouse: ADVENTUREWORKS_WAREHOUSE
  target: dev